##########################
# carbonfox palette
##########################

bg0="#0c0c0c" # Dark bg (status line and float)
bg1="#161616" # Default bg
bg2="#252525" # Lighter bg (colorcolm folds)
bg3="#353535" # Lighter bg (cursor line)
bg4="#535353" # Conceal, border fg

fg0="#f9fbff" # Lighter fg
fg1="#f2f4f8" # Default fg
fg2="#b6b8bb" # Darker fg (status line)
fg3="#7b7c7e" # Darker fg (line numbers, fold colums)

sel0="#2a2a2a" # Popup bg, visual selection bg
sel1="#525253" # Popup sel bg, search bg

comment="#6e6f70"

black0="#282828" # black base
black1="#484848" # black bright
black2="#222222" # black dim

red0="#ee5396" # red base
red1="#f16da6" # red bright
red2="#ca4780" # red dim

green0="#25be6a" # green base
green1="#46c880" # green bright
green2="#1fa25a" # green dim

yellow0="#08bdba" # yellow base
yellow1="#2dc7c4" # yellow bright
yellow2="#07a19e" # yellow dim

blue0="#78a9ff" # blue base
blue1="#8cb6ff" # blue bright
blue2="#6690d9" # blue dim

magenta0="#be95ff" # magenta base
magenta1="#c8a5ff" # magenta bright
magenta2="#a27fd9" # magenta dim

cyan0="#33b1ff" # cyan base
cyan1="#52bdff" # cyan bright
cyan2="#2b96d9" # cyan dim

white0="#dfdfe0" # white base
white1="#e4e4e5" # white bright
white2="#bebebe" # white dim

orange0="#3ddbd9" # orange base
orange1="#5ae0df" # orange bright
orange2="#34bab8" # orange dim

pink0="#ff7eb6" # pink base
pink1="#ff91c1" # pink bright
pink2="#d96b9b" # pink dim


##########################
# carbonfox theme colors
##########################

bg_color="$bg0"         # #0c0c0c
text_color="$fg1"       # #f2f4f8
accent_color="$blue0"   # #78a9ff
active_color="$fg1"     # #f2f4f8
inactive_color="$fg3"   # #7b7c7e
border_color="$bg4"     # #535353
copy_color="$yellow0"   # #08bdba
