##########################
# dawnfox palette
##########################

bg0="#ebe5df" # Dark bg (status line and float)
bg1="#faf4ed" # Default bg
bg2="#ebe0df" # Lighter bg (colorcolm folds)
bg3="#ebdfe4" # Lighter bg (cursor line)
bg4="#bdbfc9" # Conceal, border fg

fg0="#4c4769" # Lighter fg
fg1="#575279" # Default fg
fg2="#625c87" # Darker fg (status line)
fg3="#a8a3b3" # Darker fg (line numbers, fold colums)

sel0="#d0d8d8" # Popup bg, visual selection bg
sel1="#b8cece" # Popup sel bg, search bg

comment="#9893a5"

black0="#575279" # black base
black1="#5f5695" # black bright
black2="#504c6b" # black dim

red0="#b4637a" # red base
red1="#c26d85" # red bright
red2="#a5576d" # red dim

green0="#618774" # green base
green1="#629f81" # green bright
green2="#597668" # green dim

yellow0="#ea9d34" # yellow base
yellow1="#eea846" # yellow bright
yellow2="#dd9024" # yellow dim

blue0="#286983" # blue base
blue1="#2d81a3" # blue bright
blue2="#295e73" # blue dim

magenta0="#907aa9" # magenta base
magenta1="#9a80b9" # magenta bright
magenta2="#816b9a" # magenta dim

cyan0="#56949f" # cyan base
cyan1="#5ca7b4" # cyan bright
cyan2="#50848c" # cyan dim

white0="#e5e9f0" # white base
white1="#e6ebf3" # white bright
white2="#c8cfde" # white dim

orange0="#d7827e" # orange base
orange1="#de8c88" # orange bright
orange2="#ca6e69" # orange dim

pink0="#d685af" # pink base
pink1="#de8db7" # pink bright
pink2="#c9709e" # pink dim


##########################
# dawnfox theme colors
##########################

bg_color="$bg0"         # #ebe5df
text_color="$fg1"       # #575279
accent_color="$blue0"   # #286983
active_color="$fg1"     # #575279
inactive_color="$fg3"   # #a8a3b3
border_color="$bg4"     # #bdbfc9
copy_color="$yellow2"   # #dd9024
