##########################
# dayfox palette
##########################

bg0="#e4dcd4" # Dark bg (status line and float)
bg1="#f6f2ee" # Default bg
bg2="#dbd1dd" # Lighter bg (colorcolm folds)
bg3="#d3c7bb" # Lighter bg (cursor line)
bg4="#aab0ad" # Conceal, border fg

fg0="#302b5d" # Lighter fg
fg1="#3d2b5a" # Default fg
fg2="#643f61" # Darker fg (status line)
fg3="#824d5b" # Darker fg (line numbers, fold colums)

sel0="#e7d2be" # Popup bg, visual selection bg
sel1="#a4c1c2" # Popup sel bg, search bg

comment="#837a72"

black0="#352c24" # black base
black1="#534c45" # black bright
black2="#2d251f" # black dim

red0="#a5222f" # red base
red1="#b3434e" # red bright
red2="#8c1d28" # red dim

green0="#396847" # green base
green1="#577f63" # green bright
green2="#30583c" # green dim

yellow0="#ac5402" # yellow base
yellow1="#b86e28" # yellow bright
yellow2="#924702" # yellow dim

blue0="#2848a9" # blue base
blue1="#4863b6" # blue bright
blue2="#223d90" # blue dim

magenta0="#6e33ce" # magenta base
magenta1="#8452d5" # magenta bright
magenta2="#5e2baf" # magenta dim

cyan0="#287980" # cyan base
cyan1="#488d93" # cyan bright
cyan2="#22676d" # cyan dim

white0="#f2e9e1" # white base
white1="#f4ece6" # white bright
white2="#cec6bf" # white dim

orange0="#955f61" # orange base
orange1="#a57779" # orange bright
orange2="#7f5152" # orange dim

pink0="#a440b5" # pink base
pink1="#b25dc0" # pink bright
pink2="#8b369a" # pink dim


##########################
# dayfox theme colors
##########################

bg_color="$bg0"         # #e4dcd4
text_color="$fg1"       # #3d2b5a
accent_color="$blue0"   # #2848a9
active_color="$fg1"     # #3d2b5a
inactive_color="$fg3"   # #824d5b
border_color="$bg4"     # #aab0ad
copy_color="$yellow0"   # #ac5402
