##########################
# duskfox palette
##########################

bg0="#191726" # Dark bg (status line and float)
bg1="#232136" # Default bg
bg2="#2d2a45" # Lighter bg (colorcolm folds)
bg3="#373354" # Lighter bg (cursor line)
bg4="#4b4673" # Conceal, border fg

fg0="#eae8ff" # Lighter fg
fg1="#e0def4" # Default fg
fg2="#cdcbe0" # Darker fg (status line)
fg3="#6e6a86" # Darker fg (line numbers, fold colums)

sel0="#433c59" # Popup bg, visual selection bg
sel1="#63577d" # Popup sel bg, search bg

comment="#817c9c"

black0="#393552" # black base
black1="#47407d" # black bright
black2="#322e42" # black dim

red0="#eb6f92" # red base
red1="#f083a2" # red bright
red2="#d84f76" # red dim

green0="#a3be8c" # green base
green1="#b1d196" # green bright
green2="#8aa872" # green dim

yellow0="#f6c177" # yellow base
yellow1="#f9cb8c" # yellow bright
yellow2="#e6a852" # yellow dim

blue0="#569fba" # blue base
blue1="#65b1cd" # blue bright
blue2="#4a869c" # blue dim

magenta0="#c4a7e7" # magenta base
magenta1="#ccb1ed" # magenta bright
magenta2="#a580d2" # magenta dim

cyan0="#9ccfd8" # cyan base
cyan1="#a6dae3" # cyan bright
cyan2="#7bb8c1" # cyan dim

white0="#e0def4" # white base
white1="#e2e0f7" # white bright
white2="#b1acde" # white dim

orange0="#ea9a97" # orange base
orange1="#f0a4a2" # orange bright
orange2="#d6746f" # orange dim

pink0="#eb98c3" # pink base
pink1="#f0a6cc" # pink bright
pink2="#d871a6" # pink dim


##########################
# duskfox theme colors
##########################

bg_color="$bg0"         # #191726
text_color="$fg1"       # #e0def4
accent_color="$blue0"   # #569fba
active_color="$fg1"     # #e0def4
inactive_color="$fg3"   # #6e6a86
border_color="$bg4"     # #4b4673
copy_color="$yellow0"   # #f6c177
