##########################
# nightfox palette
##########################

bg0="#131a24" # Dark bg (status line and float)
bg1="#192330" # Default bg
bg2="#212e3f" # Lighter bg (colorcolm folds)
bg3="#29394f" # Lighter bg (cursor line)
bg4="#39506d" # Conceal, border fg

fg0="#d6d6d7" # Lighter fg
fg1="#cdcecf" # Default fg
fg2="#aeafb0" # Darker fg (status line)
fg3="#71839b" # Darker fg (line numbers, fold colums)

sel0="#2b3b51" # Popup bg, visual selection bg
sel1="#3c5372" # Popup sel bg, search bg

comment="#738091"

black0="#393b44" # black base
black1="#575860" # black bright
black2="#30323a" # black dim

red0="#c94f6d" # red base
red1="#d16983" # red bright
red2="#ab435d" # red dim

green0="#81b29a" # green base
green1="#8ebaa4" # green bright
green2="#6e9783" # green dim

yellow0="#dbc074" # yellow base
yellow1="#e0c989" # yellow bright
yellow2="#baa363" # yellow dim

blue0="#719cd6" # blue base
blue1="#86abdc" # blue bright
blue2="#6085b6" # blue dim

magenta0="#9d79d6" # magenta base
magenta1="#baa1e2" # magenta bright
magenta2="#8567b6" # magenta dim

cyan0="#63cdcf" # cyan base
cyan1="#7ad4d6" # cyan bright
cyan2="#54aeb0" # cyan dim

white0="#dfdfe0" # white base
white1="#e4e4e5" # white bright
white2="#bebebe" # white dim

orange0="#f4a261" # orange base
orange1="#f6b079" # orange bright
orange2="#cf8a52" # orange dim

pink0="#d67ad2" # pink base
pink1="#dc8ed9" # pink bright
pink2="#b668b2" # pink dim


##########################
# nightfox theme colors
##########################

bg_color="$bg0"         # #131a24
text_color="$fg1"       # #cdcecf
accent_color="$blue0"   # #719cd6
active_color="$fg1"     # #cdcecf
inactive_color="$fg3"   # #71839b
border_color="$bg4"     # #39506d
copy_color="$yellow0"   # #dbc074
