##########################
# nordfox palette
##########################

bg0="#232831" # Dark bg (status line and float)
bg1="#2e3440" # Default bg
bg2="#39404f" # Lighter bg (colorcolm folds)
bg3="#444c5e" # Lighter bg (cursor line)
bg4="#5a657d" # Conceal, border fg

fg0="#c7cdd9" # Lighter fg
fg1="#cdcecf" # Default fg
fg2="#abb1bb" # Darker fg (status line)
fg3="#7e8188" # Darker fg (line numbers, fold colums)
fg4="#d8dee9"

sel0="#3e4a5b" # Popup bg, visual selection bg
sel1="#4f6074" # Popup sel bg, search bg

comment="#60728a"

black0="#3b4252" # black base
black1="#465780" # black bright
black2="#353a45" # black dim

gray0="#7e8188" # gray base
gray1="#7e8188" # gray bright
gray2="#7e8188" # gray dim

white0="#e5e9f0" # white base
white1="#e7ecf4" # white bright
white2="#bbc3d4" # white dim

red0="#bf616a" # red base
red1="#d06f79" # red bright
red2="#a54e56" # red dim

green0="#a3be8c" # green base
green1="#b1d196" # green bright
green2="#8aa872" # green dim

yellow0="#ebcb8b" # yellow base
yellow1="#f0d399" # yellow bright
yellow2="#d9b263" # yellow dim

blue0="#81a1c1" # blue base
blue1="#8cafd2" # blue bright
blue2="#668aab" # blue dim

magenta0="#b48ead" # magenta base
magenta1="#c895bf" # magenta bright
magenta2="#9d7495" # magenta dim
magenta3="#c4a2bd" # magenta light

cyan0="#88c0d0" # cyan base
cyan1="#93ccdc" # cyan bright
cyan2="#69a7ba" # cyan dim

orange0="#c9826b" # orange base
orange1="#d89079" # orange bright
orange2="#b46950" # orange dim

pink0="#bf88bc" # pink base
pink1="#d092ce" # pink bright
pink2="#a96ca5" # pink dim

aqua0="#8fbcbb"
aqua1="#a3cccb"


##########################
# nordfox theme colors
##########################

bg_color="$bg0"         # #232831
text_color="$fg1"       # #cdcecf
accent_color="$blue0"   # #81a1c1
active_color="$fg1"     # #cdcecf
inactive_color="$fg3"   # #7e8188
border_color="$bg4"     # #5a657d
copy_color="$yellow0"   # #ebcb8b
