##########################
# terafox palette
##########################

bg0="#0f1c1e" # Dark bg (status line and float)
bg1="#152528" # Default bg
bg2="#1d3337" # Lighter bg (colorcolm folds)
bg3="#254147" # Lighter bg (cursor line)
bg4="#2d4f56" # Conceal, border fg

fg0="#eaeeee" # Lighter fg
fg1="#e6eaea" # Default fg
fg2="#cbd9d8" # Darker fg (status line)
fg3="#587b7b" # Darker fg (line numbers, fold colums)

sel0="#293e40" # Popup bg, visual selection bg
sel1="#425e5e" # Popup sel bg, search bg

comment="#6d7f8b"

black0="#2f3239" # black base
black1="#4e5157" # black bright
black2="#282a30" # black dim

red0="#e85c51" # red base
red1="#eb746b" # red bright
red2="#c54e45" # red dim

green0="#7aa4a1" # green base
green1="#8eb2af" # green bright
green2="#688b89" # green dim

yellow0="#fda47f" # yellow base
yellow1="#fdb292" # yellow bright
yellow2="#d78b6c" # yellow dim

blue0="#5a93aa" # blue base
blue1="#73a3b7" # blue bright
blue2="#4d7d90" # blue dim

magenta0="#ad5c7c" # magenta base
magenta1="#b97490" # magenta bright
magenta2="#934e69" # magenta dim

cyan0="#a1cdd8" # cyan base
cyan1="#afd4de" # cyan bright
cyan2="#89aeb8" # cyan dim

white0="#ebebeb" # white base
white1="#eeeeee" # white bright
white2="#c8c8c8" # white dim

orange0="#ff8349" # orange base
orange1="#ff9664" # orange bright
orange2="#d96f3e" # orange dim

pink0="#cb7985" # pink base
pink1="#d38d97" # pink bright
pink2="#ad6771" # pink dim


##########################
# terafox theme colors
##########################

bg_color="$bg0"         # #0f1c1e
text_color="$fg1"       # #e6eaea
accent_color="$blue0"   # #5a93aa
active_color="$fg1"     # #e6eaea
inactive_color="$fg3"   # #587b7b
border_color="$bg4"     # #2d4f56
copy_color="$yellow0"   # #fda47f
